services:

  deploy_test:

    container_name: deploy_test

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    expose:
      - "8080"

    networks:
      - red_global

networks:

  red_global:
    external: true