services:

  deploy_test:

    container_name: deploy_test

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      DB_URL: jdbc:mysql://mysql_global:3306/deploy_test
      DB_USER: deploy_user
      DB_PASSWORD: 123456
    ports:
      - "8080:8080"

    networks:
      - red_global

networks:

  red_global:
    external: true