name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy Application

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.VPS_HOST }}

          username: ${{ secrets.VPS_USER }}

          key: ${{ secrets.VPS_SSH_KEY }}

          port: 22

          script: |

            PROJECT_NAME="deploy_test"

            PROJECT_DIR="/srv/proyectos/$PROJECT_NAME"

            REPO_URL="https://github.com/canon4/deploy_test.git"

            echo "Verificando proyecto..."

            mkdir -p $PROJECT_DIR

            # Si no existe .git
            if [ ! -d "$PROJECT_DIR/.git" ]; then

              echo "Repositorio no inicializado"

              # Verificar si carpeta esta vacia
              if [ -z "$(ls -A $PROJECT_DIR)" ]; then

                echo "Directorio vacio. Clonando..."

                git clone $REPO_URL $PROJECT_DIR

              else

                echo "ERROR: Directorio no esta vacio"

                ls -la $PROJECT_DIR

                exit 1

              fi

            else

              echo "Repositorio existente"

              cd $PROJECT_DIR

              git config --global --add safe.directory $PROJECT_DIR

              git pull origin main

            fi

            cd $PROJECT_DIR

            echo "Construyendo contenedores..."

            docker compose up -d --build --remove-orphans

            echo "Limpiando imagenes antiguas..."

            docker image prune -f

            echo "Deploy finalizado correctamente"